### ISSUE TITLE
Connect production DNS

### ISSUE THREAD

**Issue by steveoh** [agrc/SBI#6]
Please request to the cloud machine to add the production dns to ut-dts-agrc-sbi-prod's firebase hosting. Since there is no existing DNS to swap, we can do this whenever without side effects. We will need to redirect from mapserv or inform the SBI/DFCM people of the new DNS once this is complete and work on a mapserv web server deprecation

**Comment by nathankota** [comment]
pending INC1494900

**Comment by steveoh** [comment]
LGTM
